# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    serializer:
        groups: ['Default']
    param_fetcher_listener: force
#    allowed_methods_listener:  true
#    routing_loader: true
    body_listener:
        enabled: true
    view:
        view_response_listener: force
    exception:
        enabled: true
        serializer_error_renderer: true
        messages:
            Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
            Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: true
            Symfony\Component\HttpKernel\Exception\ConflictHttpException: true
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, fallback_format: json }
