controllers:
    resource: ../../src/Controller/*
    type: annotation
    prefix: /api/v1
#wheel:
#    resource: ../../src/Controller/Wheel/*
#    type: annotation
#    prefix: /wheel
#
#inner:
#    resource: ../../src/Controller/Inner/*
#    type: annotation
#    prefix: /inner/api/v1
#
#kernel:
#    resource: ../../src/Kernel.php
#    type: annotation
